dist: trusty
sudo: required
addons:
  chrome: stable

language: node_js
node_js:
  - "lts/*"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod --aot
  - ng test